server:
  port: 83

spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    openfeign:
      # 配置httpClient5
#      httpclient:
#        hc5:
#          enabled: true
#        max-connections: 200
#        max-connections-per-route: 50
      client:
        config:
          # 全局配置
          default:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: BASIC
          # 指定服务配置
          cloud-payment-service:
            connectTimeout: 20000
            readTimeout: 20000
#消费者将要去访问的微服务名称(nacos微服务提供者叫什么你写什么)
service-url:
  nacos-user-service: http://cloud-payment-service-nacos

# 激活Sentinel对Feign的支持
feign:
  sentinel:
    enabled: true

logging:
  level:
    com.code.cloud: debug